name: Autologger

on:
  push:
    branches:
      - master

  schedule:
    - cron: '* * * * *'

jobs:
  refresh-feed:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: false

      - name: Fetch API Data 📦
        uses: JamesIves/fetch-api-data-action@1.0.19
        with:
          ENDPOINT: https://jsonplaceholder.typicode.com/todos/1
          CONFIGURATION: '{ "method": "GET" }'

      - name: Save output to folder
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          cat=`cat fetch-api-data-action/data.json`
          echo $cat > $d

      - name: Commit changes
        run: |
          git config --local user.email "theodorusclarence@gmail.com"
          git config --local user.name "Theodorus Clarence"
          git add .
          git commit -m "content:update"

      - name: Push
        uses: ad-m/github-push-action@v0.5.0
        with:
          force: true
          directory: '.'
          github_token: ${{ secrets.GITHUB_TOKEN }}
