name: Refresh Feed
on: [push]
jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch API Data 📦
        uses: JamesIves/fetch-api-data-action@1.0.19
        with:
          ENDPOINT: https://theodorusclarence.com/api/content
          CONFIGURATION: '{ "method": "GET" }'

      - name: Check output
        run: |
          d=`cat fetch-api-data-action/data.json`
          echo $d
          echo $d > OUTPUT
